
server:
  port: 8081
spring:

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/pts_gi
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
